version: '3'
services:
  factorio:
    image: my-factorio:latest
    container_name: factorio
    restart: always
    environment:
      LOAD_LATEST_SAVE: "false"
      SAVE_NAME: "main"
    volumes:
       - /opt/factorio:/factorio
    ports:
      - 34197:34197/udp


