- glances:
    url: http://localhost:61208
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cpu: true # optional, enabled by default, disable by setting to false
    mem: true # optional, enabled by default, disable by setting to false
    cputemp: true # disabled by default
    uptime: true # disabled by default
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    expanded: false # show the expanded view
    disk: /data
