version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - /opt/minecraft:/data
    environment:
      EULA: "TRUE"
