version: '3'
services:
  minecraft:
    image: my-minecraft:latest
    container_name: minecraft
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - /opt/minecraft:/data
      - /opt/perdido/config/minecraft/packwiz:/data/packwiz
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      FABRIC_VERSION: "0.14.21"
      PACKWIZ_URL: "file:///data/packwiz/pack.toml"





