version: '3'
services:
  minecraft:
    image: my-minecraft:latest
    container_name: minecraft
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - /opt/minecraft:/data
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      REMOVE_OLD: "TRUE"
      MODS_FORGEAPI_KEY:




