services:
  mumble-server:
    image: mumblevoip/mumble-server:<tag>
    container_name: mumble-server
    hostname: mumble-server
    restart: on-failure
    ports:
      - 64738:64738
      - 64738:64738/udp
  #       expose:
  #           - 6502
    volumes:
      - type: bind
        source: /data/mumble-server
        target: /data
    environment:
      - MUMBLE_CONFIG_SERVER_PASSWORD=superspecialawesomegame
      - MUMBLE_SERVER_USERNAME=recklessheroism
      - MUMBLE_SERVER_ADMIN_KEY=atroposwasneveratropos

