#!/bin/bash
# This script runs sweeper with the desired environment. It's meant to be called by rtorrent.
export SWEEPER_LOGS="/var/sweeper/logs"
export SWEEPER_WORKING_DIR="/tmp/sweeper/working_dir"
export SWEEPER_LIBRARY="/data/library"
export SWEEPER_FILEBOT="/usr/bin/filebot"
mkdir -p $SWEEPER_LIBRARY $SWEEPER_LOGS $SWEEPER_WORKING_DIR

python3.10 /opt/sweeper/run.py sweep "$@" --conflict=index --action=copy --no-subs
