---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    volumes:
      - type: bind
        source: /data/foundryvtt
        target: /data
    environment:
      - FOUNDRY_PASSWORD=superspecialawesomegame
      - FOUNDRY_USERNAME=recklessheroism
      - FOUNDRY_ADMIN_KEY=atroposwasneverwhatyouthought
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
